// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoList.Data;

#nullable disable

namespace ToDoList.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220530212409_Correcoes")]
    partial class Correcoes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ToDoList.Models.ToDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataParaConcluir")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ToDo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCriacao = new DateTime(2022, 5, 30, 22, 24, 9, 611, DateTimeKind.Local).AddTicks(9778),
                            DataParaConcluir = new DateTime(2022, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Fazer a aplicação de Adoções",
                            Titulo = "Trabalho de MVC"
                        },
                        new
                        {
                            Id = 2,
                            DataCriacao = new DateTime(2022, 5, 30, 22, 24, 9, 611, DateTimeKind.Local).AddTicks(9825),
                            DataParaConcluir = new DateTime(2022, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Fazer o FE com a api ToDo",
                            Titulo = "Trabalho de React"
                        },
                        new
                        {
                            Id = 3,
                            DataCriacao = new DateTime(2022, 5, 30, 22, 24, 9, 611, DateTimeKind.Local).AddTicks(9827),
                            DataParaConcluir = new DateTime(2022, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Ficha número 3",
                            Titulo = "Trabalho de Redes"
                        },
                        new
                        {
                            Id = 4,
                            DataConclusao = new DateTime(2022, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(2022, 5, 30, 22, 24, 9, 611, DateTimeKind.Local).AddTicks(9830),
                            DataParaConcluir = new DateTime(2022, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Ficha número 8",
                            Titulo = "Fichas de Base de Dados"
                        },
                        new
                        {
                            Id = 5,
                            DataConclusao = new DateTime(2022, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(2022, 5, 30, 22, 24, 9, 611, DateTimeKind.Local).AddTicks(9832),
                            DataParaConcluir = new DateTime(2022, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Ficha número 4",
                            Titulo = "Fichas de Sistemas Operativos"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
